# Generated by Django 2.2 on 2019-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resoursename',
            new_name='resourcename',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resoursetype',
            new_name='resourcetype',
        ),
    ]
