# Generated by Django 2.2 on 2019-05-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_auto_20190508_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'resourcetypes',
                'db_table': 'resourcetype',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourcetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubapp.ResourceType'),
        ),
    ]
